### ISSUE TITLE
CodeAnalysisRuleset not picked up on subsequent Unity restarts

### ISSUE THREAD

**Issue by NoTuxNoBux** [Unity-Technologies/com.unity.ide.vscode#20]
We are using Unity 2020.3.20 (it is the same with 2020.3.31), and have a custom Roslynator ruleset in `Assets/Scripts/Scripts.ruleset` matching a custom assembly definition `Scripts.asmdef`. It's hard to draw a straight line, but sometimes the ruleset is not picked up. I can verify this by opening `Scripts.csproj` and the line `CodeAnalysisRuleset` will not be there.

When it is picked up, doing changes in Unity or restarting it sometimes removes it again, even though the ruleset file is never (re)moved.

I've tried to reproduce it consistently, but can't. Right now the package is refusing to pick it up again; it seems random. If I find more information about how to reproduce, I will report it here, but I wanted to post the issue already since it breaks more often than it works :sweat_smile: .

**Comment by NoTuxNoBux** [comment]
I did some more testing with this. I have a project using Unity 2020.3.20f1 that already had existing `csproj` files with the analyzers in, and the `CodeAnalysisRuleset` incorrectly not added to `Scripts.csproj`. I then did the following:

1. Open project in Unity 2020.3.31f1.
2. Observe `CodeAnalysisRuleset` being added to `Scripts.csproj`. **Everything works.**
3. Remove `Scripts.csproj`.
4. Edit a file and let Unity recompile; `Scripts.csproj` was not automatically recreated.
5. Regenerate project files, which brought back `Scripts.csproj`, `CodeAnalysisRuleset` was still correctly added.
6. Restart Unity with the same project.
7. Observe `CodeAnalysisRuleset` still present in `Scripts.csproj`.
8. Update a C# script and let Unity recompile.
9. Observe `CodeAnalysisRuleset` still present.
10. Regenerate project files, `CodeAnalysisRuleset` **disappears** from `Scripts.csproj`.
11. Observe editing files or regenerating not adding it back.
12. Close Unity.
13. Clear `Library` and `Temp` project folders.
14. Open Unity again with the project.
15. Regenerate project files, `CodeAnalysisRuleset` **is added back** to `Scripts.csproj`.

So it seems there is some state or cache being maintained internally that loses the notion of the ruleset being present, but the file never actually disappears.

**Comment by NoTuxNoBux** [comment]
I dug into the source code, and it seems that, after a clean project import (step 13 above), `assembly.compilerOptions.RoslynAnalyzerRulesetPath` is properly set, but on any subsequent project starts (step 6 above), it is empty. Since this is code stemming from Unity, it is either not a bug in this package, or it is if this is intended Unity behaviour.

**Comment by miniwolf** [comment]
Can you link the public bug tracker link here @NoTuxNoBux?

**Comment by NoTuxNoBux** [comment]
@miniwolf It was just coincidentally closed a couple of days ago due to Unity not being able to reproduce this on 2020.3.35. But FWIW I think this can be closed since it no longer occurs on Unity 2021 for us, and is also wasn't a bug in this package, I think.

**Comment by miniwolf** [comment]
Good to hear, I recall fixing this in Unity. But I do not remember how long it was backported. Glad it is resolved for you.
