### ISSUE TITLE
csproj Compile-item-paths for local packages outside of Packages-folder are wrong

### ISSUE THREAD

**Issue by kraybit** [Unity-Technologies/com.unity.ide.vscode#5]
Description:
In v1.2.4 it seems paths for at least some package items look like `<Compile Include="Packages/name.of.package/etc.">`, even if the files are not in the Packages-folder.

This means local packages added with a `"file:../../LocalPackageFolder"` won't have code completion etc. in VS Code.

This worked in v1.2.3. There it seems entries like `<Compile Include="<path>">` would have an absolute path. 

Windows 10, Unity 2020.3.18f1, Visual Studio Code 1.2.4.

Repro:
- `git clone -n https://github.com/Unity-Technologies/com.unity.netcode.gameobjects.git`
- `cd com.unity.netcode.gameobjects`
- `git checkout e47b73fadfb64e81851d83fbb3a7c57a2b6baca3`
- Open the `testproject` in Unity (I used 2020.3.18f1, and updated the project..)
- (This project relies on referencing packages that are "above" the Unity project folder, so the Netcode package is actually not inside the `testproject`-folder.)
- Check that Visual Studio Code 1.2.3 is installed
- Open C# Project in VS Code
- Open `Assets/Scripts/PlayerMovement.cs` and right-click on `NetworkBehaviour` and select "Go to Definition"
- This works.
- Close VS Code
- Open the Package Manager in Unity, and update Visual Studio Code to 1.2.4
- Open C# Project again in VS Code
- `Assets/Scripts/PlayerMovement.cs` and right-click on `NetworkBehaviour` and select "Go to Definition"

What happens:
- VS Code says "No definition"
- VS Code shows endless errors for classes and stuff not being found.

**Comment by MihaPro-CarX** [comment]
I have the same problem After debugging update 1.2.4 I found the reason for this. What I wrote about in [Issue#4 ](https://github.com/Unity-Technologies/com.unity.ide.vscode/issues/4)

**Comment by miniwolf** [comment]
Fix merged to version-1.2.5
